spring.application.name=vidaanimal-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/vidaanimal_db
spring.datasource.username=vidaanimal_user
spring.datasource.password=TU_PASSWORD_ACA

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true